version: '3.8'

services:
  app:
    build: .
    container_name: spring-shop
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/shop
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  frontend:
    build:
      context: ../mydir/ShopFrontend/Shop-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ../mydir/ShopFrontend/Shop-frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    depends_on:
      - app




volumes:
  mongo-data:
  redis-data:
